config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :recipes, only: [:new, :create, :edit, :update]
  end

  resources :recipes, only: [:index, :show]

  resources :admin, only: [:index]
  post 'admin/publish/:id', to: 'admin#publish', as: 'admin_publish'
  post 'admin/unpublish/:id', to: 'admin#unpublish', as: 'admin_unpublish'
  delete 'admin/delete/:id', to: 'admin#delete', as: 'admin_delete'

  get 'welcome/about'

  devise_for :users

  root to: "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :ingredients, presence: true
  validates :directions, presence: true


  def self.published
    where(published: true)
  end

  def self.unpublished
    where(published: false)
  end

  def published?
    return self.published
  end

  def publish!
    set_publish_status(true)
  end

  def unpublish!
    set_publish_status(false)
  end

  private
  def set_publish_status(bool)
    self.published = bool
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes

  def self.grab_admin
    where(admin: true)
  end

  def make_admin!
    set_admin_status(true)
  end

  def remove_admin!
    set_admin_status(false)
  end

  private
  def set_admin_status(bool)
    self.admin = bool
    self.save
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, :user_is_admin?

  def index
    @published_recipes = Recipe.published
    @unpublished_recipes = Recipe.unpublished
  end

  def publish
    get_recipe
    @recipe.publish!
    redirect_to "/admin"
  end

  def unpublish
    get_recipe
    @recipe.unpublish!
    redirect_to "/admin"
  end

  def delete
    get_recipe
    @recipe.destroy
    redirect_to "/admin"
  end

  private
  def get_recipe
    @recipe ||= Recipe.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_is_admin?
    if current_user.admin?
    else
      redirect_to :root
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_user, only: [ :edit, :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]


  # GET /recipes
  # GET /recipes.json
  def index
      @recipes = Recipe.published
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to :root, notice: 'Recipe was successfully submitted.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.fetch(:recipe, {}).permit(:title, :ingredients, :directions)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>ADMIN PANEL</h1>
<br>
<div class='xs-block-grid-3' id="admin-published">
  <h2>Published Recipes</h2>
  <% @published_recipes.each do |recipe| %>
  <div class="block-grid__item recipe card">
    <h2><%= link_to recipe.title, recipe %></h2>
    <p>submitted by: <%= recipe.user.email %></p>
    <p>at <%= recipe.created_at.strftime("%H:%M, %b %d %Y") %></p>
    <p><%= link_to 'Read', recipe, class: "button button--secondary"%> <%= link_to 'Edit', edit_recipe_path(recipe), class: "button button--secondary" %> <%= link_to 'Delete', admin_delete_path(recipe), method: :delete, class: "button button--negative" %> <%= link_to 'Unpublish', admin_unpublish_path(recipe), method: :post, class: "button" %></p>
  </div>
  <% end %>
</div>

<div class='xs-block-grid-3 fill-gray' id="admin-unpublished">
  <h2>Unpublished Recipes</h2>
  <% @unpublished_recipes.each do |recipe| %>
  <div class="block-grid__item recipe card fill-gray">
    <h2><%= link_to recipe.title, recipe %></h2>
    <p>submitted by: <%= recipe.user.email %></p>
    <p>at <%= recipe.created_at.strftime("%H:%M, %b %d %Y") %></p>
    <p><%= link_to 'Read', recipe, class: "button button--secondary"%> <%= link_to 'Edit', edit_recipe_path(recipe), class: "button button--secondary" %> <%= link_to 'Delete', admin_delete_path(recipe), method: :delete, class: "button button--negative" %> <%= link_to 'Publish', admin_publish_path(recipe), method: :post, class: "button" %></p>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitchenette</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="fill-promoted-orange">
    <div class="clearfix">
      <div class="xs-float-left">
        <h1>Kitchenette: A Recipe App</h1>
        <%= link_to "Recipes", root_path %> /
        <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Admin", admin_index_path %> /
        <% end %>
        <%= link_to "About", welcome_about_path %>

      </div>
      <div class="xs-float-right">
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>

  </div>
</nav>
<div class="clearfix">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true, html: {class: "form"}) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label(:title, class: "form-label") %>
  <%= form.text_field(:title, class: "text-input") %>
  <%= form.label(:ingredients, class: "form-label") %>
  <%= form.text_area(:ingredients, class: "textarea") %>
  <%= form.label(:directions, class: "form-label") %>
  <%= form.text_area(:directions, class: "textarea") %>
  <br>
  <div class="actions">
    <%= form.submit("Submit Recipe", class: "button") %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div class='xs-block-grid-3'>
<% @recipes.each do |recipe| %>
    <div class="block-grid__item recipe card">
      <h2><%= link_to recipe.title, recipe %></h2>
      <p>submitted by: <%= recipe.user.email %></p>
      <p>at <%= recipe.created_at.strftime("%H:%M, %b %d %Y") %></p>
      <p><%= link_to 'Read', recipe, class: "button button--secondary"%></p>
  </div>
<% end %>
</div>

<div id="new-recipe">
<%= link_to 'New Recipe', new_recipe_path, class: "button" %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div id="recipe-title">
<h2><%= @recipe.title %></h2>
<p>submitted by: <%= @recipe.user.email %></p>
<p>at <%= @recipe.created_at.strftime("%H:%M, %b %d %Y") %></p>
</div>

<div id="recipe-ingredients">
<h3>Ingredients</h3>
<p><%= simple_format(@recipe.ingredients) %></p>
</div>

<div id="recipe-directions">
<h3>Directions</h3>
<p><%= simple_format(@recipe.directions) %></p>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Kitchenette!</h1>
<p>A simple recipe app.</p>
<br>
<h3>What it's built on:</h3>
<ul>
  <li>Rails 5</li>
  <li>Auth with Devise</li>
  <li>Buzzfeed's Solid CSS for the front end</li>
</ul>
<br>
<h3>Some Notes:</h3>
<ul>
  <li>I was unsure how much testing was required to be considered adequate, so I went ahead and tested the models to make sure that they were valid and that their methods worked. My testing experience is limited, but growing, as I recognize their importance. Going TDD was a great way to keep the project on the rails.</li>
  <li>I kept the database simple, but I would like to implement a markdown system for the next iteration. This would make the user experience/submission process more flexible. On top of that, some kind of tag system would be helpful for the user. Essentially the project would turn into a content-specific blog.</li>
  <li>Only admins can edit: Rather than allow users to manage their submissions (which would require another dashboard and set of permissions, i.e. users can only edit their own submissions), I decided that only admins could edit/modify posts. If this were a professional-grade app, users would be able to edit their own posts, but they would be seen by the admin as a "new submission", so as to avoid confusion about the content of any given submission.</li>
</ul>